openapi: 3.0.0
info:
  title: Auth API (Reference for Navigation Restructure)
  version: 1.0.0
  description: 认证相关API端点说明（本功能引用现有端点，不新增）

paths:
  /api/v1/auth/change-password:
    post:
      summary: 修改管理员密码
      description: 用于"系统设置 > 其他设置"页面的密码修改功能
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - oldPassword
                - newPassword
              properties:
                oldPassword:
                  type: string
                  description: 当前密码
                  example: "admin123"
                newPassword:
                  type: string
                  description: 新密码（至少8位）
                  minLength: 8
                  example: "newSecurePass456"
      responses:
        '200':
          description: 密码修改成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    example: 0
                  message:
                    type: string
                    example: "Password changed successfully"
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'

components:
  responses:
    BadRequest:
      description: 请求参数错误
      content:
        application/json:
          schema:
            type: object
            properties:
              code:
                type: integer
                example: 400
              message:
                type: string
                example: "New password must be at least 8 characters"
    Unauthorized:
      description: 未授权（Token无效或过期）
      content:
        application/json:
          schema:
            type: object
            properties:
              code:
                type: integer
                example: 401
              message:
                type: string
                example: "Unauthorized"
    Forbidden:
      description: 旧密码验证失败
      content:
        application/json:
          schema:
            type: object
            properties:
              code:
                type: integer
                example: 403
              message:
                type: string
                example: "Old password is incorrect"

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: []

