/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 登录并获取令牌 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        username: string;
                        /** Format: password */
                        password: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponseAuth"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 退出登录 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * @default logout
                         * @enum {string}
                         */
                        action?: "logout";
                    };
                };
            };
            responses: {
                200: components["responses"]["Ok"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取当前用户信息 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponseUser"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{id}/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 修改密码（管理员可改普通用户；普通用户只能改自己） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        old_password?: string;
                        new_password: string;
                    };
                };
            };
            responses: {
                200: components["responses"]["Ok"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 账号列表 */
        get: {
            parameters: {
                query?: {
                    page?: components["parameters"]["page"];
                    page_size?: components["parameters"]["page_size"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponseAccountList"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounts/default": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取全局默认账号 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code?: number;
                            message?: string;
                            data?: {
                                id?: string | null;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        /** 设置全局默认账号 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        id: string;
                    };
                };
            };
            responses: {
                200: components["responses"]["Ok"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounts/cookie": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 绑定账号（Cookie） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description 需包含 SESSDATA */
                        cookie: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponseAccount"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounts/qrcode": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 获取扫码登录二维码 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /**
                         * @default create
                         * @enum {string}
                         */
                        action?: "create";
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code?: number;
                            message?: string;
                            data?: {
                                session_id?: string;
                                qr_url?: string;
                                /** Format: date-time */
                                expire_at?: string;
                                /** @default 2 */
                                poll_interval_sec: number;
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounts/qrcode/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 轮询扫码登录状态 */
        get: {
            parameters: {
                query: {
                    session_id: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code?: number;
                            message?: string;
                            data?: {
                                /** @enum {string} */
                                status?: "pending" | "scanned" | "confirmed" | "expired";
                                account?: components["schemas"]["Account"];
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounts/{id}/action": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 账号操作（validate/unbind） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @enum {string} */
                        action: "validate" | "unbind";
                    };
                };
            };
            responses: {
                200: components["responses"]["Ok"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查询任务（卡片视图数据） */
        get: {
            parameters: {
                query?: {
                    page?: components["parameters"]["page"];
                    page_size?: components["parameters"]["page_size"];
                    keyword?: string;
                    type?: "video" | "author";
                    author_uid?: string;
                    tags?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponseTaskList"];
                    };
                };
            };
        };
        put?: never;
        /** 创建任务 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TaskCreate"];
                };
            };
            responses: {
                /** @description Created */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponseTask"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取任务详情 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponseTask"];
                    };
                };
            };
        };
        put?: never;
        /** 更新/删除任务（POST + action） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TaskUpdateAction"] | components["schemas"]["TaskDeleteAction"];
                };
            };
            responses: {
                200: components["responses"]["Ok"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 批量启用/禁用任务 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @enum {string} */
                        action: "enable" | "disable";
                        selection: components["schemas"]["Selection"];
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code?: number;
                            message?: string;
                            data?: {
                                success_count?: number;
                                failure_count?: number;
                                failures?: {
                                    id?: string;
                                    reason?: string;
                                }[];
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/videos/{bv}/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取视频指标时序 */
        get: {
            parameters: {
                query?: {
                    from?: string;
                    to?: string;
                    fields?: string;
                };
                header?: never;
                path: {
                    bv: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponseTimeSeries"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/videos/{bv}/insights/daily": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取视频私密指标（日粒度） */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    bv: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponseInsights"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/authors/{uid}/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取博主粉丝时序 */
        get: {
            parameters: {
                query?: {
                    from?: string;
                    to?: string;
                };
                header?: never;
                path: {
                    uid: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponseTimeSeries"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/media/videos/{bv}/cover": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取视频封面（返回本地缓存URL） */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    bv: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code?: number;
                            message?: string;
                            data?: {
                                url?: string;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/media/authors/{uid}/avatar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取博主头像（返回本地缓存URL） */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    uid: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code?: number;
                            message?: string;
                            data?: {
                                url?: string;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/media/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 手动刷新封面/头像缓存 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @enum {string} */
                        target_type: "video" | "author";
                        target_id: string;
                    };
                };
            };
            responses: {
                200: components["responses"]["Ok"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notifications/channels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取通知渠道配置 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponseChannels"];
                    };
                };
            };
        };
        put?: never;
        /** 保存通知渠道配置 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * @default save
                         * @enum {string}
                         */
                        action: "save";
                        channels: components["schemas"]["Channels"];
                    };
                };
            };
            responses: {
                200: components["responses"]["Ok"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alerts/authors/{uid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取博主粉丝告警规则 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    uid: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponseAlertRule"];
                    };
                };
            };
        };
        put?: never;
        /** 保存/禁用粉丝告警规则 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    uid: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AlertRuleSave"] | components["schemas"]["AlertRuleDisable"];
                };
            };
            responses: {
                200: components["responses"]["Ok"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查询日志 */
        get: {
            parameters: {
                query?: {
                    date?: string;
                    level?: "DEBUG" | "INFO" | "WARNING";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponseLogs"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/logs/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 下载当日日志（返回下载URL） */
        get: {
            parameters: {
                query?: {
                    date?: string;
                    level?: "DEBUG" | "INFO" | "WARNING";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code?: number;
                            message?: string;
                            data?: {
                                url?: string;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取系统设置 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponseSettings"];
                    };
                };
            };
        };
        put?: never;
        /** 保存系统设置 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * @default save
                         * @enum {string}
                         */
                        action: "save";
                        settings: components["schemas"]["Settings"];
                    };
                };
            };
            responses: {
                200: components["responses"]["Ok"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ApiResponse: {
            /** @example 0 */
            code?: number;
            /** @example ok */
            message?: string;
            data?: unknown;
        };
        ApiResponseAuth: components["schemas"]["ApiResponse"] & {
            data?: {
                token?: string;
                user?: components["schemas"]["User"];
            };
        };
        ApiResponseUser: components["schemas"]["ApiResponse"] & {
            data?: components["schemas"]["User"];
        };
        ApiResponseAccount: components["schemas"]["ApiResponse"] & {
            data?: components["schemas"]["Account"];
        };
        ApiResponseAccountList: components["schemas"]["ApiResponse"] & {
            data?: {
                items?: components["schemas"]["Account"][];
                page?: number;
                page_size?: number;
                total?: number;
            };
        };
        ApiResponseTask: components["schemas"]["ApiResponse"] & {
            data?: components["schemas"]["Task"];
        };
        ApiResponseTaskList: components["schemas"]["ApiResponse"] & {
            data?: {
                items?: components["schemas"]["Task"][];
                page?: number;
                page_size?: number;
                total?: number;
            };
        };
        ApiResponseTimeSeries: components["schemas"]["ApiResponse"] & {
            data?: {
                series?: {
                    /** Format: date-time */
                    ts?: string;
                    play?: number;
                    watching?: number;
                    danmaku?: number;
                    comment?: number;
                    coin?: number;
                    like?: number;
                }[];
            };
        };
        ApiResponseInsights: components["schemas"]["ApiResponse"] & {
            data?: {
                /** Format: date */
                date?: string;
                /** Format: float */
                completion_rate?: number;
                /** Format: float */
                avg_watch_duration_sec?: number;
            }[];
        };
        ApiResponseChannels: components["schemas"]["ApiResponse"] & {
            data?: components["schemas"]["Channels"];
        };
        ApiResponseAlertRule: components["schemas"]["ApiResponse"] & {
            data?: components["schemas"]["AlertRule"];
        };
        ApiResponseLogs: components["schemas"]["ApiResponse"] & {
            data?: {
                ts?: string;
                /** @enum {string} */
                level?: "DEBUG" | "INFO" | "WARNING";
                source?: string;
                message?: string;
            }[];
        };
        ApiResponseSettings: components["schemas"]["ApiResponse"] & {
            data?: components["schemas"]["Settings"];
        };
        Selection: {
            /** @enum {string} */
            type: "ids" | "all";
            ids?: string[];
            /** @description 与 GET /tasks 的查询参数同口径 */
            filters?: Record<string, never>;
        };
        TaskCreate: {
            /** @enum {string} */
            type: "video" | "author";
            /** @description 视频: BV号；博主: UID */
            target_id: string;
            account_id?: string | null;
            strategy?: components["schemas"]["StrategyFixed"] | components["schemas"]["StrategySmart"];
            /**
             * Format: date-time
             * @description 默认+3个月
             */
            deadline?: string;
            tags?: string[];
        };
        TaskUpdateAction: {
            /** @enum {string} */
            action: "update";
            account_id?: string | null;
            strategy?: components["schemas"]["StrategyFixed"] | components["schemas"]["StrategySmart"];
            /** Format: date-time */
            deadline?: string;
            tags?: string[];
        };
        TaskDeleteAction: {
            /** @enum {string} */
            action: "delete";
        };
        StrategyFixed: {
            /**
             * @default fixed
             * @enum {string}
             */
            mode: "fixed";
            /** @description 最小1分钟 */
            value: number;
            /** @enum {string} */
            unit: "minute" | "hour" | "day";
        };
        StrategySmart: {
            /**
             * @default smart
             * @enum {string}
             */
            mode: "smart";
        };
        Task: {
            id?: string;
            /** @enum {string} */
            type?: "video" | "author";
            target_id?: string;
            account_id?: string | null;
            /** @enum {string} */
            status?: "running" | "stopped" | "completed" | "failed" | "paused";
            /** @description 暂停原因等 */
            reason?: string | null;
            strategy?: components["schemas"]["StrategyFixed"] | components["schemas"]["StrategySmart"];
            /** Format: date-time */
            deadline?: string;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
            tags?: string[];
            latest_sample?: {
                play?: number;
                fans?: number;
                /** Format: date-time */
                last_collected_at?: string;
            };
            media?: {
                cover_url?: string | null;
                avatar_url?: string | null;
            };
        };
        User: {
            id?: string;
            username?: string;
            /** @enum {string} */
            role?: "admin" | "viewer";
        };
        Account: {
            id?: string;
            uid?: string;
            nickname?: string;
            /** @enum {string} */
            bind_method?: "cookie" | "qrcode";
            /** @enum {string} */
            status?: "valid" | "expired";
            last_failures?: number;
            /** Format: date-time */
            bound_at?: string;
        };
        Channels: {
            email?: {
                [key: string]: unknown;
            };
            dingtalk?: {
                [key: string]: unknown;
            };
            wecom?: {
                [key: string]: unknown;
            };
            webhook?: {
                [key: string]: unknown;
            };
            bark?: {
                [key: string]: unknown;
            };
            pushdeer?: {
                [key: string]: unknown;
            };
            onebot?: {
                [key: string]: unknown;
            };
            telegram?: {
                [key: string]: unknown;
            };
        };
        AlertRule: {
            /** @default false */
            enabled: boolean;
            /** @enum {string} */
            mode?: "absolute" | "percent";
            threshold?: number;
            /** @default 24 */
            window_hours: number;
        };
        AlertRuleSave: {
            /**
             * @default save
             * @enum {string}
             */
            action: "save";
            rule: components["schemas"]["AlertRule"];
        };
        AlertRuleDisable: {
            /**
             * @default disable
             * @enum {string}
             */
            action: "disable";
        };
        Settings: {
            /**
             * @description 全局最小采集间隔（分钟），可调至1分钟需提示风险
             * @default 10
             */
            min_interval_min: number;
            /** @default 1 */
            max_fixed_interval_day: number;
            /** @default 3 */
            max_retries: number;
            /** @default 20 */
            page_size_default: number;
            /** @default Asia/Shanghai */
            timezone: string;
            users?: components["schemas"]["User"][];
        };
    };
    responses: {
        /** @description OK */
        Ok: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiResponse"];
            };
        };
    };
    parameters: {
        page: number;
        page_size: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
